### ISSUE TITLE
Browser context changing after updating to 2.2

### ISSUE THREAD

**Issue by aumn26** [cheezy/page-object#460]
Hi, I'm writing tests for a page that has a footer. I have a class Footer that is locating the footer element. However, when I try to use a global browser variable, it looks like with the 2.2 upgrade and above, the @browser variable is re-initialized within the context of a new Watir element. When I was on 2.1.1, this worked:

```
def footer
    Footer.new(browser.element(css: '.Footer'))
  end
```
and then later on in the code
```
browser.element(css: '#test')
```

However, with the upgrade to 2.2, after Footer.new is called with the new element, it seems that @browser is reset to the context of the footer, so my browser.element(css: '#test') fails because it's searching for #test inside of .Footer.

Any thoughts on how to preserve the global browser context?

**Comment by Vlaaaaaaad** [comment]
Also experiencing this. When trying to do `@browser.screenshot` I get ```undefined method 'screenshot' for #<Watir::HTMLElement'``` which is totally the wrong type for `@browser`.

**Comment by thiggy1342** [comment]
Noticed a similar issue. In our case, I think it's related to a call to @browser inside of a page section (which is itself an instance of Watir::HTMLElement). I was able to work around the issue in the short term by calling `@browser.browser.method_you_want`.

**Comment by jkotests** [comment]
If I'm understanding this correctly, the issue is that the following code returned a Watir::Browser:

~~~~~~~~
gem 'page-object', '=2.1.1'
gem 'watir', '=6.7.3'
require 'watir'
require 'page-object'

class Container
    include PageObject
end

class Footer
    include PageObject
end

class MyPage
    include PageObject
    
    page_section(:container, Container, :id => 'container')
    
    def footer
        Footer.new(browser.element(css: '.Footer'))
    end

end

browser = Watir::Browser.new
browser.goto('C:\Users\Gonk\Desktop\test.htm')

page = MyPage.new(browser)

p page.footer.browser.class
#=> Watir::Browser

p page.container.browser.class
#=> Watir::Browser
~~~~~~~~

In contrast, in Page-Object v2.2+, both now return a Watir::HTMLElement.
